\hypertarget{classgdf_1_1exception_1_1bad__type__assigned__to__channel}{
\section{gdf::exception::bad\_\-type\_\-assigned\_\-to\_\-channel Class Reference}
\label{classgdf_1_1exception_1_1bad__type__assigned__to__channel}\index{gdf::exception::bad\_\-type\_\-assigned\_\-to\_\-channel@{gdf::exception::bad\_\-type\_\-assigned\_\-to\_\-channel}}
}


A member function from \hyperlink{classgdf_1_1_channel_data_base}{ChannelDataBase} was called. This should not happen and is usually caused by providing an argument with the wrong datatype to a data access function.  




{\ttfamily \#include $<$Exceptions.h$>$}

\subsection*{Public Member Functions}
\begin{DoxyCompactItemize}
\item 
\hypertarget{classgdf_1_1exception_1_1bad__type__assigned__to__channel_a60c322aa1ed352ce69e321cc87d0752d}{
{\bfseries bad\_\-type\_\-assigned\_\-to\_\-channel} (std::string str=\char`\"{}\char`\"{})}
\label{classgdf_1_1exception_1_1bad__type__assigned__to__channel_a60c322aa1ed352ce69e321cc87d0752d}

\end{DoxyCompactItemize}


\subsection{Detailed Description}
A member function from \hyperlink{classgdf_1_1_channel_data_base}{ChannelDataBase} was called. This should not happen and is usually caused by providing an argument with the wrong datatype to a data access function. 

The documentation for this class was generated from the following file:\begin{DoxyCompactItemize}
\item 
include/GDF/Exceptions.h\end{DoxyCompactItemize}
